# Generated by Django 4.1.7 on 2023-06-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateData',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=20)),
                ('Star', models.IntegerField(default=1)),
                ('Items', models.CharField(default='', max_length=100)),
                ('Augments', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('autoinc', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('playerId', models.CharField(max_length=200)),
                ('LP', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
