# Generated by Django 4.1.7 on 2023-05-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchplayers',
            name='tier',
            field=models.CharField(default='', max_length=200),
        ),
    ]
