# Generated by Django 4.1.7 on 2023-05-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0003_remove_matches_player_remove_matches_searchedplayer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
