# Generated by Django 4.1.7 on 2023-06-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0003_matches_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='traits',
            name='totaltier',
            field=models.IntegerField(default=0),
        ),
    ]
