# Generated by Django 4.1.7 on 2023-06-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0004_traits_totaltier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traits',
            old_name='totaltier',
            new_name='style',
        ),
    ]
