# Generated by Django 4.1.7 on 2023-05-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0004_delete_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='Participants',
            new_name='otherParticipants',
        ),
        migrations.RemoveField(
            model_name='searchplayers',
            name='match',
        ),
        migrations.AddField(
            model_name='matches',
            name='game_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='matches',
            name='placement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='searchedPlayer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topplayers.searchplayers'),
        ),
        migrations.AddField(
            model_name='matches',
            name='traits',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='searchplayers',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Star', models.IntegerField(default=1)),
                ('Items', models.CharField(default='', max_length=100)),
                ('associatedMatch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topplayers.matches')),
            ],
        ),
    ]
