# Generated by Django 4.1.7 on 2023-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0005_rename_participants_matches_otherparticipants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='game_length',
            field=models.CharField(default='', max_length=20),
        ),
    ]
