# Generated by Django 4.1.7 on 2023-05-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0006_matches_game_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='traits',
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitname', models.CharField(default='', max_length=100)),
                ('currenttier', models.IntegerField(default=0)),
                ('tierunits', models.IntegerField(default=0)),
                ('associatedMatch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topplayers.matches')),
            ],
        ),
    ]
