# Generated by Django 4.1.7 on 2023-06-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0006_remove_traits_tierunits_traits_imageicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champions',
            name='Items',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='traits',
            name='imageIcon',
            field=models.TextField(default='', max_length=300),
        ),
    ]
