# Generated by Django 4.1.7 on 2023-06-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0007_alter_champions_items_alter_traits_imageicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='augments',
            field=models.CharField(default='', max_length=100),
        ),
    ]
