# Generated by Django 4.1.7 on 2023-06-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0008_matches_augments'),
    ]

    operations = [
        migrations.AddField(
            model_name='champions',
            name='Item_icon',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='matches',
            name='augments_icon',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='champions',
            name='Items',
            field=models.CharField(default='', max_length=100),
        ),
    ]
