# Generated by Django 4.1.7 on 2023-06-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0009_champions_item_icon_matches_augments_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champions',
            name='ChampIcon',
            field=models.CharField(default='', max_length=800),
        ),
    ]
