# Generated by Django 4.1.7 on 2023-06-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topplayers', '0010_champions_champicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champions',
            old_name='ChampIcon',
            new_name='Champ_icon',
        ),
    ]
